cloudymc_mc_image_tag: stable-java25
cloudymc_mc_port: 25565
cloudymc_mc_additional_ports: []
cloudymc_mc_eula_accepted: false
cloudymc_mc_online_mode: true
cloudymc_mc_name: Minecraft Server
cloudymc_mc_motd: "A vanilla server running on {{ cloudymc_mc_version }}"
cloudymc_mc_icon:
cloudymc_mc_override_icon: false
cloudymc_mc_max_players: 20
cloudymc_mc_mode: survival
cloudymc_mc_version: LATEST
cloudymc_mc_difficulty: normal
cloudymc_mc_hardcore: false
cloudymc_mc_pvp: true
cloudymc_mc_level_type: normal
cloudymc_mc_seed:
cloudymc_mc_view_distance: 8
cloudymc_mc_simulation_distance: 6
cloudymc_mc_spawn_protection: 16
cloudymc_mc_allow_flight: false
cloudymc_mc_whitelist_users: []
cloudymc_mc_ops: []
cloudymc_mc_commands_startup: ["say Hello World!"]
cloudymc_mc_commands_connect: []
cloudymc_mc_commands_disconnect: []

cloudymc_mc_compose_file:
cloudymc_mc_sftp_public_key_file:
cloudymc_mc_root_path: /opt/minecraft-server
cloudymc_mc_data_path: "{{ cloudymc_mc_root_path }}/data"
cloudymc_mc_memory_mb: "{{ ansible_facts['memtotal_mb'] - 2048 }}"

cloudymc_mc_admin_user: minecraft-admin
cloudymc_mc_admin_group: minecraft-admin
cloudymc_mc_runner_user: minecraft-runner
cloudymc_mc_admin_uid: 1200
cloudymc_mc_admin_gid: 1200
cloudymc_mc_runner_uid: 1201

cloudymc_sftp_group: sftpusers
cloudymc_system_timezone: Etc/UTC
