- name: create minecraft admin group
  become: true
  ansible.builtin.group:
    name: "{{ cloudymc_mc_admin_group }}"
    gid: "{{ cloudymc_mc_admin_gid }}"
    state: present

- name: create minecraft docker runner user
  become: true
  ansible.builtin.user:
    name: "{{ cloudymc_mc_runner_user }}"
    group: "{{ cloudymc_mc_admin_group }}"
    uid: "{{ cloudymc_mc_runner_uid }}"
    shell: /bin/bash
    createhome: false
    state: present
  register: mc_user_output

- name: create minecraft admin user
  become: true
  ansible.builtin.user:
    name: "{{ cloudymc_mc_admin_user }}"
    group: "{{ cloudymc_mc_admin_group }}"
    groups: "{{ cloudymc_sftp_group }}"
    uid: "{{ cloudymc_mc_admin_uid }}"
    shell: /sbin/nologin
    create_home: true
    state: present

- name: change minecraft admin home directory permissions
  become: true
  ansible.builtin.file:
    path: /home/{{ cloudymc_mc_admin_user }}
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: remove unneeded files from the minecraft admin home directory
  become: true
  ansible.builtin.file:
    path: /home/{{ cloudymc_mc_admin_user }}/{{ item }}
    state: absent
  loop:
    - .bashrc
    - .bash_logout
    - .profile

- name: supply authorized key for the minecraft admin user
  become: true
  ansible.posix.authorized_key:
    user: "{{ cloudymc_mc_admin_user }}"
    key: "{{ lookup('ansible.builtin.file', cloudymc_sftp_public_key_file) }}"
    path: /etc/ssh/authorized_keys/{{ cloudymc_mc_admin_user }}
    exclusive: true
    state: present
